<!DOCTYPE html>
<html>
<head>
<title>TAG'S DE FORMATAÇÃO TEXTO</title>
</head>
<body>

<h1>TAG'S DE FORMATAÇÃO TEXTO</h1>
<HR>
EXEMPLOS:
<FONT FACE ="TIMES">ESSE E UM EXEMPLO DE FONTE EM TIMES NEW ROMAN</FONT>
<p>

<FONT FACE ="ARIAL">ESSE E UM EXEMPLO DE FONTE EM ARIAL</FONT>
<P>

<FONT SIZE = 8 >FONTE </FONT>
<P>

<FONT SIZE = 4 >FONTE </FONT>
<P>
<FONT SIZE=10 FACE ="ARIAL">ESSE E UM EXEMPLO DE FONTE EM ARIAL EM TAMANHO 10</FONT>
<P>

<FONT COLOR = "#BEBEBE" >FONTE CINZA </FONT>
<FONT COLOR = RED >FONTE VERMELHA </FONT>

</body>
</html>
